[package]
name = "sim8080"
version = "0.1.0"
edition = "2021"
default-run = "sim8080"

[[bin]]
name = "sim8080"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"